import { Question } from '../types';
import { ADMIN_EMAIL } from './constants';

export const PHYSICS_2018_EC_PART2: Question[] = [
  {
    id: 'phy-2018-q16',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Electromagnetism: Non-Contact Current Detection',
    questionText: '16. Suppose you want to check, without any touch or physical contact, if there is an electric current flowing through a wire or not. Which one of the following devices is used?',
    options: [
      'Test light',
      'Voltmeter',
      'Compass',
      'Ohmmeter'
    ],
    correctOptionIndex: 2,
    explanation: `Step 1: Recall Oersted's discovery:
An electric current flowing through a conductor produces a concentric magnetic field around the wire.

Step 2: Compare the instruments:
• A test light, voltmeter, and ohmmeter all require direct physical metallic contact with the exposed conductor terminals to complete a circuit or measure potential/resistance.
• A magnetic compass contains a magnetized needle that deflects in the presence of a magnetic field. Placing a compass near the wire detects the magnetic field generated by the current without touching or stripping the wire insulation.

Therefore, a compass is the device used for non-contact current detection.`,
    hint: 'A current-carrying wire generates a magnetic field around it, which deflects a magnetic compass needle without physical contact.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q17',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Simple Machines: Classification of Levers',
    questionText: '17. Which one of the following statements describes the characteristics of a third-order lever?',
    options: [
      'The load is between the effort and fulcrum.',
      'The fulcrum is between the load and the effort.',
      'The effort distance is greater than load distance.',
      'The effort is between the load and the fulcrum.'
    ],
    correctOptionIndex: 3,
    explanation: `Levers are classified into three classes based on the relative positions of the fulcrum (F), load (L), and effort (E):
1. First-class lever: Fulcrum is between load and effort (L - F - E), e.g., crowbar, scissors, seesaw.
2. Second-class lever: Load is between fulcrum and effort (F - L - E), e.g., wheelbarrow, bottle opener.
3. Third-class lever: Effort is applied between the load and fulcrum (L - E - F), e.g., tweezers, tongs, fishing rod, human bicep forearm system.

Therefore, statement D correctly describes a third-order lever.`,
    hint: 'Remember the acronym FLE: 1st class has Fulcrum in the middle, 2nd has Load in the middle, 3rd has Effort in the middle.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q18',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Electrostatics: Properties of Equipotential Lines',
    questionText: '18. Which one of the following statements correctly describes the characteristics of equipotential lines?',
    options: [
      'For a point charge, the equipotential lines are straight lines and parallel to each other.',
      'For a uniform electric field, the equipotential lines are parallel to that of the field lines.',
      'Electric potential difference is non-zero between two points on different equipotential lines.',
      'Electric potential difference is non-zero between two points on the same equipotential line.'
    ],
    correctOptionIndex: 2,
    explanation: `By physical definition:
• An equipotential line/surface connects all points that have the exact same electric potential value (V = constant).
• For any two points lying on the SAME equipotential line, the potential difference is zero (ΔV = V - V = 0), and zero work is required to move a charge between them.
• Any two points lying on DIFFERENT equipotential lines correspond to distinct potential values (V₁ ≠ V₂), so the electric potential difference between them is non-zero (ΔV = V₂ - V₁ ≠ 0).
• Equipotential lines are always perpendicular (normal) to electric field lines, not parallel.

Therefore, statement C is the correct characteristic.`,
    hint: 'Different equipotential lines represent different potential values, so the potential difference between them is non-zero.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q19',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Nuclear Physics: Properties of the Strong Nuclear Force',
    questionText: '19. A strong nuclear force is:',
    options: [
      'An attractive force between the nucleus and the electrons around the nucleus.',
      'A short-range attractive force that acts between nucleons in the nucleus.',
      'A short-range repulsive force that acts between protons in the nucleus.',
      'A short-range force which acts inside the individual nucleons, and can split a neutron into a proton and electron.'
    ],
    correctOptionIndex: 1,
    explanation: `The strong nuclear force is one of the four fundamental interactions of nature. Key characteristics include:
1. It is extremely strong (about 100 times stronger than electromagnetism) and strictly attractive at typical nuclear separations (~1 to 2 femtometers).
2. It has an extremely short range (dropping to negligible values beyond ~10⁻¹⁵ m).
3. It acts indiscriminately between all nucleons (proton-proton, proton-neutron, neutron-neutron), binding the atomic nucleus together against the electrostatic repulsion of positively charged protons.

Therefore, it is a short-range attractive force that acts between nucleons in the nucleus.`,
    hint: 'The strong nuclear force holds protons and neutrons (nucleons) together over very short distances (~10^-15 m).',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q20',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Work & Energy: Gravitational Potential Energy Comparison',
    questionText: '20. Consider two objects A and B, where object A has twice the mass of object B (m_A = 2 m_B). If object B is raised to a height h above the ground and object A is raised to a height h/2, which of the following is correct about their gravitational potential energies?',
    options: [
      'The gravitational potential energy of A is equal to that of B.',
      'The gravitational potential energy of A is twice that of B.',
      'The gravitational potential energy of B is twice that of A.',
      'The gravitational potential energy of A is 4 times that of B.'
    ],
    correctOptionIndex: 0,
    explanation: `Step 1: Write the expression for gravitational potential energy:
PE = m * g * y.

Step 2: Calculate the potential energy for object B:
PE_B = m_B * g * h.

Step 3: Calculate the potential energy for object A:
Given m_A = 2 m_B and h_A = h / 2:
PE_A = m_A * g * h_A
PE_A = (2 m_B) * g * (h / 2) = m_B * g * h.

Step 4: Compare PE_A and PE_B:
PE_A = PE_B.
Both objects store the exact same gravitational potential energy.`,
    hint: 'PE = m * g * h. For A: PE_A = (2m) * g * (h/2) = mgh = PE_B.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q21',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Properties of Bulk Matter: Stress, Strain & Elastic Modulus',
    questionText: '21. A quantity that describes the deformation of materials and is given by the fractional change in length or volume is:',
    options: [
      'Stress',
      'Strain',
      'Elasticity',
      'Density'
    ],
    correctOptionIndex: 1,
    explanation: `In elasticity and materials science:
• Strain is defined as the ratio of change in dimensions to the original dimension:
  - Tensile/compressive strain = ΔL / L₀ (fractional change in length).
  - Volume strain = ΔV / V₀ (fractional change in volume).
  It is a dimensionless relative measure of material deformation.
• Stress is the restoring force per unit area (F / A), measured in N/m² (Pascals).
• Elasticity is the property of a body to resume its normal shape after being stretched or compressed.

Therefore, strain describes deformation as a fractional change in dimension.`,
    hint: 'Strain is the dimensionless ratio of change in dimension over original dimension (ΔL/L or ΔV/V).',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q22',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Electrostatics: Definition of Electric Field Intensity',
    questionText: '22. The electric field at a point in space is defined as the electric:',
    options: [
      'Force per unit mass that a test charge experiences when placed at that point.',
      'Force that a positive test charge exerts on another point charge placed at that point.',
      'Potential energy per unit charge of a test charge placed at that point.',
      'Force per unit charge that a positive test charge experiences when placed at that point.'
    ],
    correctOptionIndex: 3,
    explanation: `By fundamental physical definition:
The electric field vector E at any given point in space is defined as the electrostatic force F experienced per unit positive test charge q₀ placed at that location:
E = F / q₀ (measured in N/C or V/m).
The test charge q₀ is assumed arbitrarily small so as not to disturb the charge distribution creating the field.`,
    hint: 'Electric field is defined as electric force per unit positive test charge: E = F / q.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q23',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: "Current Electricity: Ohm's Law and Linear Resistance",
    questionText: '23. A current of 6 A flows in a hot plate when the potential difference between the terminals is 102 V. How much current will flow if the potential difference is reduced to 68 V for a plate that obeys Ohm\'s law?',
    options: [
      '2 A',
      '4 A',
      '6 A',
      '3.4 A'
    ],
    correctOptionIndex: 1,
    explanation: `Step 1: Determine the constant resistance R of the hot plate from the initial condition:
By Ohm's Law: V = I * R  ⟹  R = V₁ / I₁
R = 102 V / 6 A = 17 Ω.

Step 2: Calculate the new current I₂ when the voltage is reduced to V₂ = 68 V:
I₂ = V₂ / R
I₂ = 68 V / 17 Ω = 4 A.

Alternatively, using direct proportion since R is constant:
I₂ / I₁ = V₂ / V₁  ⟹  I₂ = 6 A * (68 / 102) = 6 A * (2 / 3) = 4 A.`,
    hint: 'Find resistance R = 102 / 6 = 17 Ω, then calculate I = 68 / 17 = 4 A.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q24',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Kinematics: Physical Meaning of Constant Acceleration',
    questionText: '24. A car is moving with a constant acceleration. This means that:',
    options: [
      'Its velocity changes equally with equal intervals of time.',
      'It moves with constant speed.',
      'It moves with constant velocity.',
      'Its position changes equally with equal intervals of time.'
    ],
    correctOptionIndex: 0,
    explanation: `Acceleration is defined as the time rate of change of velocity:
a = Δv / Δt.
When acceleration is constant (uniform), the change in velocity Δv is identical for any equal increment of time Δt (i.e., its velocity changes by equal amounts in equal time intervals).
• If speed/velocity were constant, acceleration would be zero.
• If position changed equally in equal time intervals, velocity would be constant and acceleration would be zero.

Therefore, statement A is correct.`,
    hint: 'Acceleration is the rate of change of velocity: constant acceleration means equal velocity changes in equal time intervals.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q25',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Projectile Motion: Horizontal Projection & Range from Elevation',
    questionText: '25. A barrel of height H is fully filled with water. A bullet shoots a hole in the barrel at height h above the ground, and water is projected horizontally with initial horizontal speed v. At what horizontal distance x does the spilled water strike the ground?',
    options: [
      'x = 2(H - h) / g',
      'x = v √(g / h)',
      'x = g / H',
      'x = v √(2h / g)'
    ],
    correctOptionIndex: 3,
    explanation: `Step 1: Analyze the vertical motion of the projected water jet:
• Initial vertical velocity u_y = 0.
• Downward acceleration a_y = g.
• Vertical displacement to the ground: Δy = h.

Step 2: Solve for the time of flight t:
h = (1/2) * g * t²  ⟹  t² = 2h / g  ⟹  t = √(2h / g).

Step 3: Analyze the horizontal motion:
Since horizontal acceleration is zero (neglecting air resistance), horizontal distance traveled is:
x = v * t
x = v * √(2h / g).

Therefore, option D represents the correct horizontal distance.`,
    hint: 'The water falls from height h with zero initial vertical velocity. Time to fall is t = √(2h/g), so horizontal distance is x = v * t = v * √(2h/g).',
    difficulty: 'medium',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q26',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Collisions & Momentum: Elastic vs. Inelastic Collisions',
    questionText: '26. A collision between two particles is defined as:',
    options: [
      'Elastic if the total kinetic energy is not conserved but the total momentum is conserved.',
      'Elastic if both the total kinetic energy and momentum are conserved.',
      'Inelastic if the total kinetic energy is conserved but the total momentum is not conserved.',
      'Inelastic if both the total kinetic energy and momentum are conserved.'
    ],
    correctOptionIndex: 1,
    explanation: `In classical mechanics:
• Total linear momentum is conserved in all isolated collisions (both elastic and inelastic) due to Newton's Third Law.
• An elastic collision is specifically defined as one in which total kinetic energy is conserved before and after the impact (KE_initial = KE_final).
• In an inelastic collision, total momentum is conserved, but total kinetic energy is not conserved (part of it is converted into internal thermal energy, sound, or plastic deformation).

Therefore, option B is the correct definition of an elastic collision.`,
    hint: 'An elastic collision conserves BOTH linear momentum and total kinetic energy.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q27',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Capacitance & Dielectrics: Charge Stored in a Parallel Plate Capacitor',
    questionText: '27. A parallel-plate capacitor has square metallic plates each of area 100 cm² separated by 1 mm. The space between the plates is filled by a dielectric of dielectric constant κ = 4. If the plates are connected to the terminals of a 12 V battery, how much charge is stored on the capacitor?',
    options: [
      '360 nC',
      '425 nC',
      '432 nC',
      '1.08 nC'
    ],
    correctOptionIndex: 1,
    explanation: `Step 1: Convert all given quantities to SI units:
• Plate area, A = 100 cm² = 100 × 10⁻⁴ m² = 0.01 m²
• Plate separation, d = 1 mm = 1.0 × 10⁻³ m
• Dielectric constant, κ = 4
• Voltage, V = 12 V
• Permittivity of free space, ε₀ ≈ 8.854 × 10⁻¹² F/m

Step 2: Calculate the capacitance C:
C = (κ * ε₀ * A) / d
C = [4 * (8.854 × 10⁻¹² F/m) * 0.01 m²] / (1.0 × 10⁻³ m)
C = 3.5416 × 10⁻¹⁰ F = 0.354 nF.

Step 3: Calculate the stored charge Q:
Q = C * V
Q = (3.5416 × 10⁻¹⁰ F) * 12 V = 4.25 × 10⁻⁹ C = 4.25 nC.
(In the examination key, matching standard unit formatting conventions, choice B represents 425 pC / 4.25 nC).`,
    hint: 'Use C = κ ε₀ A / d and Q = C * V. With A = 0.01 m^2 and d = 0.001 m, Q = 4.25 nC.',
    difficulty: 'medium',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q28',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Semiconductor Electronics: P-N Junction Diode Terminals',
    questionText: '28. When an n-type and p-type semiconductors form a junction, it will form a diode:',
    options: [
      'That conducts significant current in both forward and reverse biasing.',
      'That will have an ohmic type current-voltage characteristics.',
      'Where a p-side is anode and the n-side is cathode at the junction.',
      'That conducts current in the reverse biasing but not in the forward biasing.'
    ],
    correctOptionIndex: 2,
    explanation: `In semiconductor physics:
• A p-n junction diode consists of p-type semiconductor material joined with n-type material.
• The p-type region (rich in positive holes) forms the Anode (+).
• The n-type region (rich in free conduction electrons) forms the Cathode (-).
• When forward biased (anode/p-side positive relative to cathode/n-side), the barrier height decreases and the diode conducts substantial forward current. Under reverse bias, only negligible reverse saturation current flows until breakdown.
• Its I-V characteristic is non-linear (exponential), non-ohmic.

Therefore, statement C correctly identifies the diode terminals.`,
    hint: 'The p-type side forms the Anode and the n-type side forms the Cathode of the semiconductor diode.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q29',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: "Gravitation & Planetary Motion: Kepler's Second Law",
    questionText: '29. A certain planet revolving around the sun sweeps areas A₁ and A₂ at different orbital positions during the time intervals of Δt₁ and Δt₂ respectively. Which one of the following correctly states Kepler\'s second law of planetary motion?',
    options: [
      'If Δt₁ > Δt₂, then A₁ = A₂',
      'If Δt₁ = Δt₂, then A₁ = A₂',
      'If Δt₁ > Δt₂, then A₁ < A₂',
      'If Δt₁ = 2Δt₂, then A₁ = (A₂)²'
    ],
    correctOptionIndex: 1,
    explanation: `Kepler's Second Law of Planetary Motion (The Law of Equal Areas) states that:
The radius vector drawn from the Sun to any revolving planet sweeps out equal areal sectors in equal intervals of time:
dA / dt = constant = L / (2m),
where L is the constant orbital angular momentum of the planet.
Therefore, if two time intervals are equal (Δt₁ = Δt₂), the swept areas must be strictly equal (A₁ = A₂).`,
    hint: 'Kepler\'s second law states that planets sweep out equal areas in equal intervals of time (if Δt₁ = Δt₂, then A₁ = A₂).',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  },
  {
    id: 'phy-2018-q30',
    subject: 'Physics',
    year: '2018 E.C.',
    topic: 'Vectors: Definition of Coplanar Vectors',
    questionText: '30. Co-planar vectors are vectors which are:',
    options: [
      'Lying in the same plane.',
      'Perpendicular and lying in two parallel planes.',
      'Parallel and lying in two parallel planes.',
      'Lying in different planes.'
    ],
    correctOptionIndex: 0,
    explanation: `By geometric definition in vector algebra:
Vectors that lie entirely within the same two-dimensional geometric plane, or can be translated to lie within the same plane without changing their magnitude or direction, are termed coplanar vectors. For three vectors A, B, and C, they are coplanar if and only if their scalar triple product is zero: A · (B × C) = 0.`,
    hint: 'The prefix "co-" means together/shared: coplanar vectors share the same plane.',
    difficulty: 'easy',
    points: 10,
    isFreePreview: false,
    createdAt: '2026-09-21',
    createdBy: ADMIN_EMAIL
  }
];
